[project]
authors = ["Jermiah <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "radiomics-orcestra2"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.6,<4"
snakemake = ">=8.20.5,<9"
snakemake-executor-plugin-kubernetes = ">=0.2.1,<0.3"
snakemake-storage-plugin-gcs = ">=1.1.1,<2"
